# Generated by Django 4.1.5 on 2023-01-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_blogcategory_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog", name="date", field=models.DateTimeField(null=True),
        ),
    ]
