# Generated by Django 4.1.5 on 2023-01-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_blog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="date", field=models.DateTimeField(null=True),
        ),
    ]
