# Generated by Django 4.1.5 on 2023-01-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_blog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog", name="front_body", field=models.TextField(blank=True),
        ),
    ]
