# Generated by Django 4.1.5 on 2023-01-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_blog_front_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog", name="slug", field=models.TextField(blank=True),
        ),
    ]
