# Generated by Django 4.1.5 on 2023-01-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_blogcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
